PKGDIR       ?= ../..
L4DIR        ?= $(PKGDIR)/../..

TARGET	      = libi2c-server.a libi2c-server.so
SRC_CC        = i2c_server.cc
PC_FILENAME   = i2c-server
REQUIRES_LIBS = libstdc++ l4virtio

include $(L4DIR)/mk/lib.mk
